builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
brews:
- folder: Formula
  github:
    owner: caarlos0
    name: homebrew-tap
  description: Get the contributor stats summary from all repos of any given organization
nfpms:
- formats:
    - deb
snapcrafts:
- publish: true
  summary: Get the contributor stats summary from all repos of any given organization
  description: |
    Get the contributor stats summary from all repos of any given organization
  grade: stable
