language: go
go: 1.7.1
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - go test -cover `glide nv`
  - go run main.go getantibody
after_success:
  test ! -z "$TRAVIS_TAG" && wget -O - https://raw.githubusercontent.com/caarlos0/go-releaser/master/release | bash -s -- -u caarlos0 -r org-stats -b org-stats -m .
notifications:
  email: false
