language: go
go: 1.7.4
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - go test -cover `glide nv`
  - go run main.go --org getantibody
after_success:
  - gem install fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
