language: go
go: 1.7.4
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - go test -cover `glide nv`
  - go run main.go --org getantibody
after_success:
  - go get github.com/goreleaser/goreleaser
  - gem install fpm
  - test -n "$TRAVIS_TAG" && goreleaser
notifications:
  email: false
