language: go
go: 1.13.x
addons:
  apt:
    packages:
    - snapd
env:
- PATH=/snap/bin:$PATH
install: make setup
script:
- make ci
- "./org-stats --org goreleaser --blacklist get --top 10"
after_success:
- go get github.com/mattn/goveralls
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
- test -n "$TRAVIS_TAG" && sudo snap install snapcraft --classic
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_5a326c51f06f_key -iv $encrypted_5a326c51f06f_iv
  -in snap.login.enc -out snap.login -d
