name: generate

on:
  push:
    branches:
      - 'master'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: docs
        run: ./scripts/docs.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update cmd docs"
